// GENERATED by scripts/light-enamel.mjs — do not edit; re-run the script.

/** The library's navy enamel, measured: mean of every re-inked pixel. */
export const NAVY_ENAMEL = "#1A2747";

/** The ivory the twins are re-inked with (its full-light value). */
export const IVORY_ENAMEL = "#F3F0E8";

/** Badges (file names under /tiles/high-school/) with an ivory twin in ./light/. */
export const LIGHT_ENAMEL_FILES: readonly string[] = [
  "bowling",
  "campus-ministry",
  "cheer",
  "chess",
  "choir",
  "color-guard",
  "crest",
  "crew",
  "debate",
  "diploma-cap",
  "drama",
  "esports",
  "field-hockey",
  "film",
  "grad-cap",
  "gymnastics",
  "honor-star",
  "journalism",
  "lacrosse",
  "marching-band",
  "medal",
  "model-un",
  "orchestra",
  "photography",
  "quiz-bowl",
  "racquetball",
  "robotic-arm",
  "robotics",
  "rotc",
  "rugby",
  "scouts",
  "service",
  "ski",
  "star",
  "swim-dive",
  "torch",
  "track",
  "trophy",
  "water-polo",
  "weightlifting",
  "wrestling",
  "yearbook",
];
